language: node_js
node_js:
- "stable"
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: "$EMAIL"
  api_key: "$API_KEY"
  skip_cleanup: true
  on:
    tags: true
    repo: AntonioArts/data-form-react